CREATE TABLE JOUEURS (
  id INTEGER PRIMARY KEY,
  login VARCHAR2(50) UNIQUE,
  mdp VARCHAR2(200) NOT NULL
);

CREATE TABLE ROLE(
  login VARCHAR2(50) UNIQUE,
  role VARCHAR2(200) NOT NULL CHECK role IN ([listeRole])
);
